routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('admin', 'IndexController@index')->name('login'); // for redirection purpose


/*Route::name('/')->group(
    function () {*/

        Route::get('/', 'IndexController@index');
        Route::group(['middleware' => 'backendAuthenticate'], function () {

            Route::get('/dashboard', [
                'uses' => 'DashboardController@index',
                'as' => 'dashboard.index'
            ]);

            Route::group(['middleware' => ['backendAuthenticate','PermissionHandler']], function () {


                ###role management routes###
                Route::resource('role', 'RoleController');
                Route::get('role/set-permissions/{role}', 'RoleController@setPermissions')->name('role.set-permissions');
                Route::post('role/set-permissions/update/{role}', 'RoleController@setPermissionsUpdate')->name('role.set-permissions.update');

                ###Sub Admins###
                Route::get('sub-admin/data', 'SubAdminController@data')->name('sub-admin.data');
                Route::resource('sub-admin', 'SubAdminController');
                Route::get('sub-admin/active/{record}', 'SubAdminController@active')->name('sub-admin.active');
                Route::get('sub-admin/inactive/{record}', 'SubAdminController@inactive')->name('sub-admin.inactive');


                Route::get('zones/data', 'ZonesController@data')->name('zones.data');
                Route::resource('zones', 'ZonesController');


                Route::get('work-time/data', 'WorkTimeController@data')->name('work-time.data');
                Route::resource('work-time', 'WorkTimeController');


                Route::get('work-type/data', 'WorkTypeController@data')->name('work-type.data');
                Route::resource('work-type', 'WorkTypeController');

                Route::get('joey-document-verification/data', 'JoeyDocumentVerificationController@data')->name('joey-document-verification.data');
                Route::resource('joey-document-verification', 'JoeyDocumentVerificationController');
                Route::get('joeyDocumentVerification/status/update/statusUpdate', 'JoeyDocumentVerificationController@statusUpdate')->name('joey-document-verification.statusUpdate');


                Route::get('training/data', 'TrainingController@data')->name('training.data');
                Route::resource('training', 'TrainingController');

                Route::get('categores/data', 'CategoresController@data')->name('categores.data');
                Route::resource('categores', 'CategoresController');


                Route::get('quiz-management/data', 'QuizController@data')->name('quiz-management.data');
                Route::resource('quiz-management', 'QuizController');


                Route::get('job-type/data', 'JobTypeController@data')->name('job-type.data');
                Route::resource('job-type', 'JobTypeController');


                Route::get('order-category/data', 'OrderCategoryController@data')->name('order-category.data');
                Route::resource('order-category', 'OrderCategoryController');

                Route::get('vendors/data', 'VendorsController@data')->name('vendors.data');
                Route::resource('vendors', 'VendorsController');

                Route::get('joey-checklist/data', 'JoeyChecklistController@data')->name('joey-checklist.data');
                Route::resource('joey-checklist', 'JoeyChecklistController');


                Route::get('basic-vendor/data', 'BasicVendorController@data')->name('basic-vendor.data');
                Route::resource('basic-vendor', 'BasicVendorController');


                Route::get('basic-category/data', 'BasicCategoryController@data')->name('basic-category.data');
                Route::resource('basic-category', 'BasicCategoryController');

                Route::get('vendor-score/data', 'VendorScoreController@data')->name('vendor-score.data');
                Route::resource('vendor-score', 'VendorScoreController');

                Route::get('category-score/data', 'CategoryScoreController@data')->name('category-score.data');
                Route::resource('category-score', 'CategoryScoreController');


                Route::resource('site-settings', 'SiteSettingsController');
                Route::resource('countries', 'CountriesController');
                Route::resource('cities', 'CitiesController');


                Route::get('/edit-profile', [
                    'uses' => 'UsersController@editProfile',
                    'as' => 'users.edit-profile'
                ]);

                Route::post('/edit-profile', [
                    'uses' => 'UsersController@updateEditProfile',
                    'as' => 'users.edit-profile'
                ]);


                Route::get('/change-password', [
                    'uses' => 'UsersController@changePassword',
                    'as' => 'users.change-password'
                ]);


                Route::post('/change-password', [
                    'uses' => 'UsersController@processChangePassword',
                    'as' => 'users.change-password'
                ]);
            });
        }
        );
          Route::get('/login', [
                'uses' => 'Auth\LoginController@showLoginForm',
                'as' => 'login'
            ]);

        Route::post('/login', [
            'uses' => 'Auth\LoginController@login',
            'as' => 'login'
        ]);


        Route::any('/logout', [
            'uses' => 'Auth\LoginController@logout',
            'as' => 'logout'
        ]);

        Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
        Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('reset-password', 'auth\ResetPasswordController@reset_password_from_show')->name('reset.password.show');
        Route::post('reset-password-update', 'auth\Resetpasswordcontroller@reset_password_update')->name('reset.password.update');
  //}
//);

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Auth::routes();

Route::get('/', 'HomeController@index')->name('index');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::post('contact', 'HomeController@processContact')->name('process-contact');
Route::get('categories/{slug}', 'HomeController@categoryDetails')->name('category.details');

Route::get('home', function () {
    return redirect('/');
});

Route::get('thank-you', function () {
    return view('thankYou');
});

/*Route::get('/clear-cache', function() {
	Artisan::call('cache:clear');
   	Artisan::call('config:clear');
	Artisan::call('config:cache');
	Artisan::call('view:clear');
	Artisan::call('route:clear');
	return 'Cache cleared!';
});*/

routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
Route::get('reset/success', function (Request $request) {
    return view('admin.auth.passwords.success');
});
Route::get('joeyco-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('apidocs', static function (Request $request) {
    return view('documentation.index');
});

Route::get('json-file', static function(Request $request){


    //Get Json File
    $file = file_get_contents(base_path('webservices.json'));

    $decodeFile =  json_decode($file, true);

    //Replace Host With Current Host
    $decodeFile['host'] = request()->getHttpHost();

    //Set Base Path
    $decodeFile['basePath'] = str_replace('json-file', 'api/v1', request()->getRequestUri());

    //Set Scheme According To Request
    $decodeFile['schemes'] = $request->isSecure() ? ['https'] : ['http'];

    return response()->json($decodeFile);

})->name('json-url');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;




use App\Mail\WelcomeMail;
use App\Models\Interfaces\UserInterface;
use Carbon\Carbon;
use DB;
use http\Url;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Support\Facades\Mail;

class User extends Authenticatable implements UserInterface, JWTSubject
{

    public $table = 'onboarding_users';

    use SoftDeletes,Notifiable;

    public const ROLE_ADMIN       = 'admin';



    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','full_name','user_name','email', 'address','password','city','country','role_id','status','phone','device_token','device_type','push_status','profile_picture','is_verify','verify_token','rights','permissions',
        'userType','first_name','last_name','education_type','emergency_contact','guardian_name','guardian_phone','notification_status','mobile_no','location_country','location_latitude','location_longitude','bio','social_media_id',
        'dob','is_verified','last_login','verify_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
    ];


    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }


    /**
     * Scope a query to only include active users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNotAdmin($query)
    {
        $admin_role_id =  config('app.super_admin_role_id');
        return $query->where('role_id', '!=',$admin_role_id);
    }

    /*
 * @User related methods
 */
    public function validateUserActiveCriteria() : bool
    {
        if((int)$this->attributes['is_active'] === 0){

            if((int)$this->attributes['is_unblock'] === 0){
                //throw new \Mockery\Exception('Your account has been blocked by the admin, please contact '. constants('global.site.name').' admin');
                throw new \App\Exceptions\UserNotAllowedToLogin('Your account has been blocked by the admin, please contact ', 'account_block');
            }
            if((int)$this->attributes['is_verified'] === 0){
                //throw new \Mockery\Exception('Your account has not been verify by the admin, please contact '. constants('global.site.name').' admin');
                throw new \App\Exceptions\UserNotAllowedToLogin('Your account has not been verify by the admin, please contact ', 'account_verify');
            }

            if((int)$this->attributes['email_verified'] !== 1){
                //throw new \Mockery\Exception('Your email is not verified please verify your email first.');
                throw new \App\Exceptions\UserNotAllowedToLogin('Your email is not verified please verify your email first.', 'account_email_verify');
            }

            if((int)$this->attributes['sms_verified'] !== 1){
                //throw new \Mockery\Exception('Please verify your mobile number first, it\'s not verified.');
                throw new \App\Exceptions\UserNotAllowedToLogin('Please verify your mobile number first, it\'s not verified.', 'account_sms_verify');
            }

            //throw new \Mockery\Exception('Your account is inactive, please contact '. constants('global.site.name').' admin');
            throw new \App\Exceptions\UserNotAllowedToLogin('Your account is inactive, please contact '. constants('global.site.name').' admin', 'account_active');
        }

        return true;

    }

    public function deactivate() : void
    {
        $this->status  = 0;
        $this->save();
    }

    public function activate() : void
    {
        $this->status  = 1;
        $this->save();
    }

    public function getStatusTextFormattedAttribute() : string
    {
        return (int)$this->attributes['status'] === 1 ?
            '<a href="'. route('sub-admin.inactive', $this->attributes['id']) .'"><span class="label label-success">Active</span></a>' :
            '<a href="'. route('sub-admin.active', $this->attributes['id']) .'"><span class="label label-warning">Inactive</span></a>';
    }

    public function sendPasswordResetNotification($token)
    {

        $this->notify(new \App\Notifications\Backend\AdminResetPasswordNotification($token));
    }



    public function getPhoneFormattedAttribute()
    {
        return $this->attributes['phone'] ? phone($this->attributes['phone'])->formatNational() : '';// $this->attributes['phone'] : '';
    }

/*    public function getProfilePictureAttribute() {
        $file = $this->attributes['profile_picture'];
        return is_file(backendUserFile().$file) ? backendUserUrl($file) : backendUserUrl(constants('front.default.admin'));
    }*/

 /*   public function getProfilePictureAutoAttribute() : string
    {
        $file = $this->attributes['profile_picture'];
        return is_file(backendUserFile().$file) ? $file : constants('front.default.admin');
    }*/


    /**
     * Get current permissions user.
     *
     * @return array
     */
    public function getPermissions()
    {
        return $this->Permissions->pluck('route_name')->toArray();
    }


    /**
     * Get dashboard cards rights user.
     *
     * @return array
     */
    public function getDashboardCardsPermissionsArray()
    {
        $data = $this->Role->pluck('dashbaord_cards_rights');
        dd($data);
    }



    /**
     * Get the role of user.
     *
     * @return array
     */

    public function Role()
    {
        return $this->belongsTo(Roles::class, 'role_id','id');
    }



    /**
     * Get the role of user.
     *
     * @return array
     */

    public function DashboardCardRightsArray()
    {
        $rights = false;
        $data = $this->Role()->pluck('dashbaord_cards_rights')->first();

        if($this->role_id == Permissions::GetSuperAdminRole())
        {
            return true;
        }

        if($data != null && $data != '')
        {
            $rights = explode(',',$data);

        }

        return $rights;

    }

    /**
     * Get the role permissions .
     *
     * @return array
     */

    public function Permissions()
    {
        return $this->hasMany(Permissions::class, 'role_id','role_id');
    }


    /**
     * Get permissions data extracted .
     *
     * @return array
     */

    public function PermissionsExtract()
    {
        return $this->hasMany(Permissions::class, 'role_id','role_id')->pluck('route_name')->toArray();
    }

 public  function sendWelcomeEmail()
 {
     $email = $this->attributes['email'];
     $name = $this->attributes['full_name'];
     $token = uniqid(Str::random(64),true);

 /*    DB::table(config('auth.passwords.users.table'))->insert([
         'email' => $email,
         'token' => $token,
         'created_at' => Carbon::now()
     ]);*/
     DB::table('password_resets')->insert([
         'email' => $email,
         'token' => $token,
         'created_at' => Carbon::now()
     ]);

     $resetUrl = url('/reset-password?email='.$email.'&token='.$token.'');

     return  $this->notify(new \App\Notifications\Backend\ResetPasswordEmailSend($resetUrl,$name));

 }

}

resources/views/admin/subAdmin/action.blade.php
@if(can_access_route('sub-admin.show',$userPermissoins))
<a style="background-color: #e36d28;" href="{{route('sub-admin.show', base64_encode ($record->id)) }}" title="Detail"
   class="btn btn-xs btn-primary">
    <i class="fa fa-eye"></i>
</a>
@endif

@if(can_access_route('sub-admin.edit',$userPermissoins))
<a href="{{route('sub-admin.edit', base64_encode ($record->id))}}" title="Edit"
     class="btn btn-xs btn-info">
       <i class="fa fa-pencil-square"></i>
</a>
@endif

@if(can_access_route('sub-admin.destroy',$userPermissoins))
<a class="btn btn-xs btn-danger delete" type="button" title="Delete" data-toggle="modal"
   data-target="#deleteModal{{ $record->id }}">
    <i class="fa fa-trash-o"></i>
</a>


<div id="deleteModal{{ $record->id }}" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete sub admin?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                {!! Form::model($record, ['method' => 'delete',  'url' => 'sub-admin/'.$record->id, 'class' =>'form-inline form-delete']) !!}
                {!! Form::hidden('id', $record->id) !!}
                {!! Form::submit('Yes', ['class' => 'btn btn-success btn-flat']) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endif

resources/views/admin/subAdmin/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">{{ $pageTitle }} <small></small></h3>
        {{ Breadcrumbs::render('sub-admin.edit', $sub_admin) }}
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<link href="{{ asset('assets/admin/css/customPreview.css') }}" rel="stylesheet" type="text/css"/>
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">

        @include('admin.partials.errors')

        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">

            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-edit"></i> {{ $pageTitle }}
                </div>
            </div>

            <div class="portlet-body">

                <h4>&nbsp;</h4>

                <form method="POST" action="{{ route('sub-admin.update', $sub_admin->id) }}" class="form-horizontal" role="form" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="first_name" class="col-md-2 control-label">First Name *</label>
                        <div class="col-md-4">
                            <input type="text" name="first_name" maxlength="150" value="{{ old('first_name', $sub_admin->first_name) }}"
                                   class="form-control"/>
                        </div>
                        @if ($errors->has('first_name'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="last_name" class="col-md-2 control-label">Last Name *</label>
                        <div class="col-md-4">
                            <input type="text" name="last_name" maxlength="32" value="{{ old('last_name', $sub_admin->last_name) }}"
                                   class="form-control"/>
                        </div>
                        @if ($errors->has('last_name'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-md-2 control-label">Email *</label>
                        <div class="col-md-4">
                            <input type="text" name="email" maxlength="32" value="{{ old('email', $sub_admin->email) }}"
                                   class="form-control" readonly/>
                        </div>
                        @if ($errors->has('email'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="phone" class="col-md-2 control-label">Phone *</label>
                        <div class="col-md-4">
                            <input type="text" name="phone" maxlength="32" value="{{ old('phone', $sub_admin->phone_formatted) }}"
                                   class="form-control phone_us"/>
                        </div>
                        @if ($errors->has('phone'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="address" class="col-md-2 control-label">Address (Optional)</label>
                        <div class="col-md-4">
                            <input type="text" name="address" maxlength="32" value="{{ old('address', $sub_admin->address) }}"
                                   class="form-control"/>
                        </div>
                        @if ($errors->has('address'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="rights" class="col-md-2 control-label">Role Type *</label>
                        <div class="col-md-4">
                            <select class="form-control col-md-7 col-xs-12 role-type" name="role" required>
                                <option value="">Select an option</option>
                                @foreach($role_list as $role)
                                    <option value="{{$role->id}}">{{$role->display_name}}</option>
                                @endforeach
                            </select>
                        </div>
                        @if ($errors->has('role'))
                            <span class="help-block">
                                    <strong>{{ $errors->first('role') }}</strong>
                                </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="password" class="col-md-2 control-label">Password *</label>
                        <div class="col-md-4">
                            <input type="password" name="password" maxlength="32" value=""
                                   class="form-control"/>
                        </div>
                        @if ($errors->has('password'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                        @endif

                    </div>


                    <div class="form-group">
                    <div>

                        {{ Form::label('upload_file', 'Upload Picture *', ['class'=>'col-md-2 control-label']) }}
                        <div class="col-md-4">
                            {{ Form::file('upload_file', ['class' => 'form-control ']) }}
                            <img style="max-width: 350px;height: 150px;" onClick="preview(this);"  src="{{$sub_admin->profile_picture}}" />

                        </div>
                        @if ( $errors->has('upload_file') )
                            <p class="help-block">{{ $errors->first('upload_file') }}</p>
                        @endif


                    </div>
                    </div>
                   {{-- <div class="form-group">
                        <label for="confirm_password" class="col-md-2 control-label">Confirm Password *</label>
                        <div class="col-md-4">
                            <input type="password" name="confirm_password" value="" class="form-control" />
                        </div>
                        @if ($errors->has('confirm_password'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('confirm_password') }}</strong>
                                    </span>
                        @endif
                    </div>--}}


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn blue" id="save" value="Save">
                            <input type="button" class="btn black" name="cancel" id="cancel" value="Cancel">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
<!-- END PAGE CONTENT-->
@stop

@section('footer-js')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('assets/admin/scripts/core/app.js') }}"></script>
<script src="{{ asset('assets/admin/scripts/custom/customPreview.js') }}"></script>

<script>

    jQuery(document).ready(function() {
   // initiate layout and plugins
   App.init();
   Admin.init();
   $('#cancel').click(function() {
        window.location.href = "{{ route('sub-admin.index') }}";
   });
});

$(document).ready(function() {

    $('.phone_us').mask('(000) 000-0000', {placeholder: "(___) ___-____"});
    make_option_selected('.role-type','{{ old('role',$sub_admin->role_id) }}');
});
</script>
@stop

resources/views/admin/subAdmin/image.blade.php
    <img class="img-thumbnail"  onClick="preview(this);"  src="{{$record->profile_picture}}"/>

resources/views/admin/subAdmin/status.blade.php
@if(can_access_route(['sub-admin.active','sub-admin.inactive'],$userPermissoins))
    @if($record->status === 1)
    <a  class="btn btn-xs" type="button" data-toggle="modal"
        data-target="#statusModal{{ $record->status }}">
        <span class="label label-success">Active</span>
    </a>

    <div id="statusModal{{ $record->status }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirm Status?</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to change the status?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    {!! Form::model($record, ['method' => 'get',  'url' => 'sub-admin/inactive/'.$record->id, 'class' =>'form-inline form-edit']) !!}
                    {!! Form::hidden('id', $record->id) !!}
                    {!! Form::submit('Yes', ['class' => 'btn btn-success btn-flat']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

    @else
    <a  class="btn btn-xs" type="button" data-toggle="modal"
        data-target="#statusModal{{ $record->status }}">
    <span class="label label-warning">In Active</span>
    </a>


    <div id="statusModal{{ $record->status }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirm Status?</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to change the status?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    {!! Form::model($record, ['method' => 'get',  'url' => 'sub-admin/active/'.$record->id, 'class' =>'form-inline form-edit']) !!}
                    {!! Form::hidden('id', $record->id) !!}
                    {!! Form::submit('Yes', ['class' => 'btn btn-success btn-flat']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

    @endif
@endif