routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('admin', 'IndexController@index')->name('login'); // for redirection purpose


/*Route::name('/')->group(
    function () {*/

        Route::get('/', 'IndexController@index');
        Route::group(['middleware' => 'backendAuthenticate'], function () {

            Route::get('/dashboard', [
                'uses' => 'DashboardController@index',
                'as' => 'dashboard.index'
            ]);

            Route::group(['middleware' => ['backendAuthenticate','PermissionHandler']], function () {


                ###role management routes###
                Route::resource('role', 'RoleController');
                Route::get('role/set-permissions/{role}', 'RoleController@setPermissions')->name('role.set-permissions');
                Route::post('role/set-permissions/update/{role}', 'RoleController@setPermissionsUpdate')->name('role.set-permissions.update');

                ###Sub Admins###
                Route::get('sub-admin/data', 'SubAdminController@data')->name('sub-admin.data');
                Route::resource('sub-admin', 'SubAdminController');
                Route::get('sub-admin/active/{record}', 'SubAdminController@active')->name('sub-admin.active');
                Route::get('sub-admin/inactive/{record}', 'SubAdminController@inactive')->name('sub-admin.inactive');


                Route::get('zones/data', 'ZonesController@data')->name('zones.data');
                Route::resource('zones', 'ZonesController');


                Route::get('work-time/data', 'WorkTimeController@data')->name('work-time.data');
                Route::resource('work-time', 'WorkTimeController');


                Route::get('work-type/data', 'WorkTypeController@data')->name('work-type.data');
                Route::resource('work-type', 'WorkTypeController');

                Route::get('joey-document-verification/data', 'JoeyDocumentVerificationController@data')->name('joey-document-verification.data');
                Route::resource('joey-document-verification', 'JoeyDocumentVerificationController');
                Route::get('joeyDocumentVerification/status/update/statusUpdate', 'JoeyDocumentVerificationController@statusUpdate')->name('joey-document-verification.statusUpdate');


                Route::get('training/data', 'TrainingController@data')->name('training.data');
                Route::resource('training', 'TrainingController');

                Route::get('categores/data', 'CategoresController@data')->name('categores.data');
                Route::resource('categores', 'CategoresController');


                Route::get('quiz-management/data', 'QuizController@data')->name('quiz-management.data');
                Route::resource('quiz-management', 'QuizController');


                Route::get('job-type/data', 'JobTypeController@data')->name('job-type.data');
                Route::resource('job-type', 'JobTypeController');


                Route::get('order-category/data', 'OrderCategoryController@data')->name('order-category.data');
                Route::resource('order-category', 'OrderCategoryController');

                Route::get('vendors/data', 'VendorsController@data')->name('vendors.data');
                Route::resource('vendors', 'VendorsController');

                Route::get('joey-checklist/data', 'JoeyChecklistController@data')->name('joey-checklist.data');
                Route::resource('joey-checklist', 'JoeyChecklistController');


                Route::get('basic-vendor/data', 'BasicVendorController@data')->name('basic-vendor.data');
                Route::resource('basic-vendor', 'BasicVendorController');


                Route::get('basic-category/data', 'BasicCategoryController@data')->name('basic-category.data');
                Route::resource('basic-category', 'BasicCategoryController');

                Route::get('vendor-score/data', 'VendorScoreController@data')->name('vendor-score.data');
                Route::resource('vendor-score', 'VendorScoreController');

                Route::get('category-score/data', 'CategoryScoreController@data')->name('category-score.data');
                Route::resource('category-score', 'CategoryScoreController');


                Route::resource('site-settings', 'SiteSettingsController');
                Route::resource('countries', 'CountriesController');
                Route::resource('cities', 'CitiesController');


                Route::get('/edit-profile', [
                    'uses' => 'UsersController@editProfile',
                    'as' => 'users.edit-profile'
                ]);

                Route::post('/edit-profile', [
                    'uses' => 'UsersController@updateEditProfile',
                    'as' => 'users.edit-profile'
                ]);


                Route::get('/change-password', [
                    'uses' => 'UsersController@changePassword',
                    'as' => 'users.change-password'
                ]);


                Route::post('/change-password', [
                    'uses' => 'UsersController@processChangePassword',
                    'as' => 'users.change-password'
                ]);
            });
        }
        );
          Route::get('/login', [
                'uses' => 'Auth\LoginController@showLoginForm',
                'as' => 'login'
            ]);

        Route::post('/login', [
            'uses' => 'Auth\LoginController@login',
            'as' => 'login'
        ]);


        Route::any('/logout', [
            'uses' => 'Auth\LoginController@logout',
            'as' => 'logout'
        ]);

        Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
        Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('reset-password', 'auth\ResetPasswordController@reset_password_from_show')->name('reset.password.show');
        Route::post('reset-password-update', 'auth\Resetpasswordcontroller@reset_password_update')->name('reset.password.update');
  //}
//);

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Auth::routes();

Route::get('/', 'HomeController@index')->name('index');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::post('contact', 'HomeController@processContact')->name('process-contact');
Route::get('categories/{slug}', 'HomeController@categoryDetails')->name('category.details');

Route::get('home', function () {
    return redirect('/');
});

Route::get('thank-you', function () {
    return view('thankYou');
});

/*Route::get('/clear-cache', function() {
	Artisan::call('cache:clear');
   	Artisan::call('config:clear');
	Artisan::call('config:cache');
	Artisan::call('view:clear');
	Artisan::call('route:clear');
	return 'Cache cleared!';
});*/

routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
Route::get('reset/success', function (Request $request) {
    return view('admin.auth.passwords.success');
});
Route::get('joeyco-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('apidocs', static function (Request $request) {
    return view('documentation.index');
});

Route::get('json-file', static function(Request $request){


    //Get Json File
    $file = file_get_contents(base_path('webservices.json'));

    $decodeFile =  json_decode($file, true);

    //Replace Host With Current Host
    $decodeFile['host'] = request()->getHttpHost();

    //Set Base Path
    $decodeFile['basePath'] = str_replace('json-file', 'api/v1', request()->getRequestUri());

    //Set Scheme According To Request
    $decodeFile['schemes'] = $request->isSecure() ? ['https'] : ['http'];

    return response()->json($decodeFile);

})->name('json-url');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/quizManagement/action.blade.php
{{--<a href="{!! URL::route('admin.pages.show', $record->id) !!}" title="Detail"
   class="btn btn-xs btn-primary">
    <i class="fa fa-eye"></i>
</a>--}}
@if(can_access_route('quiz-management.edit',$userPermissoins))
    <a href="{!! URL::route('quiz-management.edit', $record->id) !!}" title="Edit"
       class="btn btn-xs btn-primary">
        <i class="fa fa-pencil-square"></i>
    </a>
@endif
@if(can_access_route('quiz-management.delete',$userPermissoins))
    <a class="btn btn-xs btn-danger delete" type="button" title="Delete" data-toggle="modal"
       data-target="#deleteModal{{ $record->id }}">
        <i class="fa fa-trash-o"></i>
    </a>


    <div id="deleteModal{{ $record->id }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirm Delete</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this quiz?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    {!! Form::model($record, ['method' => 'delete',  'url' => 'admin/quiz-management/'.$record->id, 'class' =>'form-inline form-delete']) !!}
                    {!! Form::hidden('id', $record->id) !!}
                    {!! Form::submit('Yes', ['class' => 'btn btn-success btn-flat']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endif

resources/views/admin/quizManagement/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">{{ $pageTitle ?? '' }} <small></small></h3>
        {{ Breadcrumbs::render('quiz-management.create') }}
        <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->

    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">

        {{--@include('admin.partials.errors')--}}

        <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet box blue">

                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i> {{ $pageTitle ?? '' }}
                    </div>
                </div>

                <div class="portlet-body">

                    <h4>&nbsp;</h4>
                    <form method="POST" action="{{ route('quiz-management.store') }}" class="form-horizontal"
                          role="form">
                        @csrf
                        @method('POST')
                        <div class="form-group">
                            <label class="col-md-2 control-label ">Type *</label>
                            <div name="type" class="col-md-4">
                                <label>
                                    <input type="radio" class="cat_type" name="type" value="orderCategoryDD"  />By Order Category</label>

                                <label>
                                    <input type="radio" class="cat_type" name="type" value="vendorDD" />By Vendor</label>
                            </div>
                            @if ($errors->has('type'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Select *</label>
                            <div class="justshow col-md-4">

                                <select id="" name="" class="form-control col-md-7 col-xs-12">
                                    required </select>
                            </div>
                            <div class="orderCategoryDD col-md-4" hidden>

                                <select id="order_category_id" name="order_category_id"
                                        class="form-control col-md-7 col-xs-12" required>

                                    @foreach($order_categories as $oc)
                                        <option value="{{$oc->id}}">{{$oc->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                            <div class="vendorDD col-md-4" hidden>


                                <select id="vendor_id" name="vendor_id" class="form-control col-md-7 col-xs-12"
                                        required>

                                    @foreach($vendors as $v)
                                        <option value="{{$v->id}}">{{$v->first_name}}</option>
                                    @endforeach

                                </select>
                            </div>

                        </div>


                        <div class="form-group">
                            <label class="col-md-2 control-label">Question *</label>
                            <div class="col-md-4">
                                <textarea name='question' id='question' rows="10"  class='form-control form-control col-md-7 col-xs-12'
                                          placeholder='Question..' >{{old('question')}}</textarea>
                            </div>
                            @if ($errors->has('question'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('question') }}</strong>
                                    </span>
                            @endif
                        </div>


                        <div class="form-group" id='ans1'>
                            <label class="col-md-2 control-label">Options *</label>
                            <div name="answers"class="col-md-4">
                                <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                       name='ans[]' id='ans1' class='form-control'  placeholder='Answer1..'   value="{{ old('ans.0') }}" required/>
                                <br>
                                <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                       name='ans[]' id='ans2' class='form-control' placeholder='Answer2..' value="{{ old('ans.1') }}" required/>
                                <br>
                                <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                       name='ans[]' id='ans3' class='form-control' placeholder='Answer3..' value="{{ old('ans.2') }}" required/>
                                <br>
                                <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                       name='ans[]' id='ans4' class='form-control' placeholder='Answer4..'  value="{{ old('ans.3') }}" required/>
                            </div>

                            <div style="     margin-left: 25px;" class="col-md-1">
                                <label><input type='radio' id='right1' name='right' value="1" required >a.</label>
                                <br>
                                <br>
                                <br>
                                <label><input type='radio' id='right2' name='right' value="2" required>b.</label>
                                <br>
                                <br>
                                <br>
                                <label><input type='radio' id='right3' name='right' value="3" required>c.</label>
                                <br>
                                <br>
                                <br>
                                <label><input type='radio' id='right4' name='right' value="4" required>d.</label>
                            </div>
                        </div>

                        <div class="form-group" style="    padding-left: 131px;">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn blue" id="save" value="Save">
                                <input type="button" class="btn black" name="cancel" id="cancel" value="Cancel">
                            </div>
                        </div>


                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
    <!-- END PAGE CONTENT-->
@stop

@section('footer-js')
    <script type="text/javascript" src="{{ asset('assets/admin/plugins/ckeditor/ckeditor.js') }}"></script>
    <script src="{!! URL::to('assets/admin/scripts/core/app.js') !!}"></script>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css"
          integrity="sha256-b5ZKCi55IX+24Jqn638cP/q3Nb2nlx+MH/vMMqrId6k=" crossorigin="anonymous"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"
        integrity="sha256-5YmaxAwMjIpMrVlK84Y/+NjCpKnFYa8bWWBbUHSBGfU=" crossorigin="anonymous"></script>
    <script>
        jQuery(document).ready(function () {

            // initiate layout and plugins
            App.init();
            Admin.init();
            $('#cancel').click(function () {
                window.location.href = "{!! URL::route('quiz-management.index') !!}";
            });
        });
        $(document).ready(function () {
            $('#submit').click(function () {
                var radios = $('input[type=radio]')
                var current = radios.filter(':checked');
                var next = radios.eq(radios.index(current) + 1);
                if (next.length === 0) {
                    next = radios.first();
                }
                next.prop('checked', true);
            });
        });

        $('.cat_type').change(function () {
            let selected_val = $(this).val();

            if (selected_val == 'orderCategoryDD') {

                document.getElementById('order_category_id').selectedIndex = 0;
                $(".orderCategoryDD").show();
                $(".vendorDD").hide();
                $(".justshow").hide();
            } else {
                document.getElementById('vendor_id').selectedIndex = 0;
                $(".orderCategoryDD").hide();
                $(".vendorDD").show();
                $(".justshow").hide();
            }
        });

    </script>
    <script type="text/javascript">

    </script>
@stop

resources/views/admin/quizManagement/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">{{ $pageTitle ?? '' }} <small></small></h3>
        {{ Breadcrumbs::render('quiz-management.edit', $quizManagement ?? '') }}
        <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">

        @include('admin.partials.errors')

        <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet box blue">

                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i> {{ $pageTitle ?? '' }}
                    </div>
                </div>

                <div class="portlet-body">

                    <div class="portlet-body">

                        <h4>&nbsp;</h4>

                        <form method="POST"
                              action="{{ route('quiz-management.update', $quizManagement->id) }}"
                              class="form-horizontal" role="form">
                            @csrf
                            @method('PUT')


                            <div class="form-group">
                                <label class="col-md-2 control-label">Question *</label>
                                <div class="col-md-4">
                                <textarea name='question' id='someid' rows="10"
                                          class='form-control form-control col-md-7 col-xs-12'
                                          placeholder='Question..'  required>{{ $quizManagement->question}}</textarea>
                                </div>
                                @if ($errors->has('question'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('question') }}</strong>
                                    </span>
                                @endif
                            </div>


                            <div class="form-group" id='ans1'>
                                <label class="col-md-2 control-label">Options *</label>
                                <div class="col-md-4">
                                    <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                           name='ans[]' id='ans1' class='form-control' placeholder='Answer1..'
                                           value="{{$dataQuizAnswer[0]['answer']}}" required/>
                                    <input type='hidden' name='old-id[]' value="{{$dataQuizAnswer[0]['id']}}"/>
                                    <br>
                                    <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                           name='ans[]' id='ans2' class='form-control' placeholder='Answer2..'
                                           value="{{$dataQuizAnswer[1]['answer']}}" required/>
                                    <input type='hidden' name='old-id[]' value="{{$dataQuizAnswer[1]['id']}}"/>
                                    <br>
                                    <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                           name='ans[]' id='ans3' class='form-control' placeholder='Answer3..'
                                           value="{{$dataQuizAnswer[2]['answer']}}" required/>
                                    <input type='hidden' name='old-id[]' value="{{$dataQuizAnswer[2]['id']}}"/>
                                    <br>
                                    <input type='text' style="margin-bottom: 10px; padding-bottom: 12px; width: 500px;"
                                           name='ans[]' id='ans4' class='form-control' placeholder='Answer4..'
                                           value="{{$dataQuizAnswer[3]['answer']}}" required/>
                                    <input type='hidden' name='old-id[]' value="{{$dataQuizAnswer[3]['id']}}"/>
                                </div>

                                <div style="     margin-left: 25px;"   class="col-md-1">
                                    <label><input type='radio' id='right1' name='right'
                                                  value={{$dataQuizAnswer[0]['id']}}
                                                  @if($dataQuizAnswer[0]['id'] == $quizManagement->correct_answer_id) checked @endif
                                        >a.</label>
                                    <br>
                                    <br>
                                    <br>
                                    <label><input type='radio' id='right2' name='right'
                                                  value={{$dataQuizAnswer[1]['id']}}
                                                  @if($dataQuizAnswer[1]['id'] == $quizManagement->correct_answer_id) checked @endif
                                        >b.</label>
                                    <br>
                                    <br>
                                    <br>
                                    <label><input type='radio' id='right3' name='right'
                                                  value={{$dataQuizAnswer[2]['id']}}
                                                  @if($dataQuizAnswer[2]['id'] == $quizManagement->correct_answer_id) checked @endif
                                        >c.</label>
                                    <br>
                                    <br>
                                    <br>
                                    <label><input type='radio' id='right4' name='right'
                                                  value={{$dataQuizAnswer[3]['id']}}
                                                  @if($dataQuizAnswer[3]['id'] == $quizManagement->correct_answer_id) checked @endif
                                        >d.</label>
                                </div>
                            </div>
                    <div class="form-group" style="    padding-left: 131px;">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn blue" id="save" value="Save">
                            <input type="button" class="btn black" name="cancel" id="cancel" value="Cancel">
                        </div>
                    </div>
                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
    <!-- END PAGE CONTENT-->
@stop

@section('footer-js')
    {{--<script type="text/javascript" src="{!! URL::to('assets/admin/plugins/ckeditor/ckeditor.js') !!}"></script>--}}
    <script src="{{ asset('assets/admin/scripts/core/app.js')}}"></script>
    <script>
        jQuery(document).ready(function () {
            // initiate layout and plugins
            App.init();
            Admin.init();
            $('#cancel').click(function () {
                window.location.href = "{!! URL::route('quiz-management.index') !!}";
            });

        });


    </script>
@stop