routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('admin', 'IndexController@index')->name('login'); // for redirection purpose


/*Route::name('/')->group(
    function () {*/

        Route::get('/', 'IndexController@index');
        Route::group(['middleware' => 'backendAuthenticate'], function () {

            Route::get('/dashboard', [
                'uses' => 'DashboardController@index',
                'as' => 'dashboard.index'
            ]);

            Route::group(['middleware' => ['backendAuthenticate','PermissionHandler']], function () {


                ###role management routes###
                Route::resource('role', 'RoleController');
                Route::get('role/set-permissions/{role}', 'RoleController@setPermissions')->name('role.set-permissions');
                Route::post('role/set-permissions/update/{role}', 'RoleController@setPermissionsUpdate')->name('role.set-permissions.update');

                ###Sub Admins###
                Route::get('sub-admin/data', 'SubAdminController@data')->name('sub-admin.data');
                Route::resource('sub-admin', 'SubAdminController');
                Route::get('sub-admin/active/{record}', 'SubAdminController@active')->name('sub-admin.active');
                Route::get('sub-admin/inactive/{record}', 'SubAdminController@inactive')->name('sub-admin.inactive');


                Route::get('zones/data', 'ZonesController@data')->name('zones.data');
                Route::resource('zones', 'ZonesController');


                Route::get('work-time/data', 'WorkTimeController@data')->name('work-time.data');
                Route::resource('work-time', 'WorkTimeController');


                Route::get('work-type/data', 'WorkTypeController@data')->name('work-type.data');
                Route::resource('work-type', 'WorkTypeController');

                Route::get('joey-document-verification/data', 'JoeyDocumentVerificationController@data')->name('joey-document-verification.data');
                Route::resource('joey-document-verification', 'JoeyDocumentVerificationController');
                Route::get('joeyDocumentVerification/status/update/statusUpdate', 'JoeyDocumentVerificationController@statusUpdate')->name('joey-document-verification.statusUpdate');


                Route::get('training/data', 'TrainingController@data')->name('training.data');
                Route::resource('training', 'TrainingController');

                Route::get('categores/data', 'CategoresController@data')->name('categores.data');
                Route::resource('categores', 'CategoresController');


                Route::get('quiz-management/data', 'QuizController@data')->name('quiz-management.data');
                Route::resource('quiz-management', 'QuizController');


                Route::get('job-type/data', 'JobTypeController@data')->name('job-type.data');
                Route::resource('job-type', 'JobTypeController');


                Route::get('order-category/data', 'OrderCategoryController@data')->name('order-category.data');
                Route::resource('order-category', 'OrderCategoryController');

                Route::get('vendors/data', 'VendorsController@data')->name('vendors.data');
                Route::resource('vendors', 'VendorsController');

                Route::get('joey-checklist/data', 'JoeyChecklistController@data')->name('joey-checklist.data');
                Route::resource('joey-checklist', 'JoeyChecklistController');


                Route::get('basic-vendor/data', 'BasicVendorController@data')->name('basic-vendor.data');
                Route::resource('basic-vendor', 'BasicVendorController');


                Route::get('basic-category/data', 'BasicCategoryController@data')->name('basic-category.data');
                Route::resource('basic-category', 'BasicCategoryController');

                Route::get('vendor-score/data', 'VendorScoreController@data')->name('vendor-score.data');
                Route::resource('vendor-score', 'VendorScoreController');

                Route::get('category-score/data', 'CategoryScoreController@data')->name('category-score.data');
                Route::resource('category-score', 'CategoryScoreController');


                Route::resource('site-settings', 'SiteSettingsController');
                Route::resource('countries', 'CountriesController');
                Route::resource('cities', 'CitiesController');


                Route::get('/edit-profile', [
                    'uses' => 'UsersController@editProfile',
                    'as' => 'users.edit-profile'
                ]);

                Route::post('/edit-profile', [
                    'uses' => 'UsersController@updateEditProfile',
                    'as' => 'users.edit-profile'
                ]);


                Route::get('/change-password', [
                    'uses' => 'UsersController@changePassword',
                    'as' => 'users.change-password'
                ]);


                Route::post('/change-password', [
                    'uses' => 'UsersController@processChangePassword',
                    'as' => 'users.change-password'
                ]);
            });
        }
        );
          Route::get('/login', [
                'uses' => 'Auth\LoginController@showLoginForm',
                'as' => 'login'
            ]);

        Route::post('/login', [
            'uses' => 'Auth\LoginController@login',
            'as' => 'login'
        ]);


        Route::any('/logout', [
            'uses' => 'Auth\LoginController@logout',
            'as' => 'logout'
        ]);

        Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
        Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('reset-password', 'auth\ResetPasswordController@reset_password_from_show')->name('reset.password.show');
        Route::post('reset-password-update', 'auth\Resetpasswordcontroller@reset_password_update')->name('reset.password.update');
  //}
//);

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Auth::routes();

Route::get('/', 'HomeController@index')->name('index');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::post('contact', 'HomeController@processContact')->name('process-contact');
Route::get('categories/{slug}', 'HomeController@categoryDetails')->name('category.details');

Route::get('home', function () {
    return redirect('/');
});

Route::get('thank-you', function () {
    return view('thankYou');
});

/*Route::get('/clear-cache', function() {
	Artisan::call('cache:clear');
   	Artisan::call('config:clear');
	Artisan::call('config:cache');
	Artisan::call('view:clear');
	Artisan::call('route:clear');
	return 'Cache cleared!';
});*/

routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
Route::get('reset/success', function (Request $request) {
    return view('admin.auth.passwords.success');
});
Route::get('joeyco-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('apidocs', static function (Request $request) {
    return view('documentation.index');
});

Route::get('json-file', static function(Request $request){


    //Get Json File
    $file = file_get_contents(base_path('webservices.json'));

    $decodeFile =  json_decode($file, true);

    //Replace Host With Current Host
    $decodeFile['host'] = request()->getHttpHost();

    //Set Base Path
    $decodeFile['basePath'] = str_replace('json-file', 'api/v1', request()->getRequestUri());

    //Set Scheme According To Request
    $decodeFile['schemes'] = $request->isSecure() ? ['https'] : ['http'];

    return response()->json($decodeFile);

})->name('json-url');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/WorkTime.php
<?php

namespace App\Models;
use App\Models\Interfaces\WorkTimeInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class WorkTime extends Model implements WorkTimeInterface
{

    public $table = 'prefer_work_times';

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'start_time',
        'end_time',
        'created_at',
        'updated_at',
        'deleted_at',
        'joey_id',

    ];


    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
    ];


    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */


}

app/Http/Controllers/Admin/WorkTimeController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Requests\Admin\StoreWorkTimeRequest;
use App\Http\Requests\Admin\UpdateWorkTimeRequest;
use App\Models\WorkTime;
use App\Repositories\Interfaces\WorkTimeRepositoryInterface;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class WorkTimeController extends Controller
{
    private $workTimeRepository;

    /**
     * Create a new controller instance.
     *
     * @param WorkTimeRepositoryInterface $workTimeRepository
     */


    public function __construct(WorkTimeRepositoryInterface $workTimeRepository)
    {
        $this->middleware('auth:admin');
        parent::__construct();
        $this->workTimeRepository = $workTimeRepository;
    }


    public function index()
    {

        return view('admin.workTime.index');
    }

    public function data(DataTables $datatables, Request $request) : JsonResponse
    {
        $query  = WorkTime::query();

        return $datatables->eloquent($query)
            ->setRowId(static function ($record) {
                return $record->id;
            })

            ->addColumn('action', static function ($record) {
                return backend_view('workTime.action', compact('record') );
            })
            ->rawColumns(['is_active'])
            ->make(true);
    }


    public function create()
    {
        return view('admin.workTime.create');
    }


    public function store(StoreWorkTimeRequest $request){
        $data=$request->all();
        $workTimeRecord = [
            'start_time' => $data['startTime'],
            'end_time' => $data['endTime'],
        ];

        $this->workTimeRepository->create($workTimeRecord);
        return redirect()
            ->route('work-time.index')
            ->with('success', 'Work time added successfully.');
    }



    public function edit(WorkTime $workTime){
        return view('admin.workTime.edit',compact('workTime'));
    }

    public function update (UpdateWorkTimeRequest $updateWorkTimeRequest,WorkTime $workTime){

        $workTimeData = $updateWorkTimeRequest->all();
        dd($workTimeData);
        $updateWorkTimeRecord = [
            'start_time' => $workTimeData['start_time'],
            'end_time' => $workTimeData['end_time'],

        ];

        $this->workTimeRepository->update($workTime->id, $updateWorkTimeRecord);
        return redirect()
            ->route('work-time.index')
            ->with('success', 'Work time updated successfully.');
    }

    public function destroy(WorkTime $workTime)
    {
        $data = $workTime->delete();
        return redirect()
            ->route('work-time.index')
            ->with('success', 'Work time was removed successfully.');
    }

}

resources/views/admin/workTime/action.blade.php
@if(can_access_route('work-time.edit',$userPermissoins))
    <a href="{!! URL::route('work-time.edit', $record->id) !!}" title="Edit"
       class="btn btn-xs btn-primary">
        <i class="fa fa-pencil-square"></i>
    </a>
@endif
@if(can_access_route('work-time.delete',$userPermissoins))
    <a class="btn btn-xs btn-danger delete" type="button" title="Delete" data-toggle="modal"
       data-target="#deleteModal{{ $record->id }}">
        <i class="fa fa-trash-o"></i>
    </a>


    <div id="deleteModal{{ $record->id }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirm Delete</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this work time?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    {!! Form::model($record, ['method' => 'delete',  'url' => 'admin/work-time/'.$record->id, 'class' =>'form-inline form-delete']) !!}
                    {!! Form::hidden('id', $record->id) !!}
                    {!! Form::submit('Yes', ['class' => 'btn btn-success btn-flat']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endif

resources/views/admin/workTime/create.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">{{ $pageTitle ?? '' }} <small></small></h3>
        {{ Breadcrumbs::render('work-time.create') }}
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->

<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">

        {{--@include('admin.partials.errors')--}}

        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">

            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i> {{ $pageTitle ?? '' }}
                </div>
            </div>

            <div class="portlet-body">

                <h4>&nbsp;</h4>
                <form method="POST" action="{{ route('work-time.store') }}" class="form-horizontal" role="form">
                    @csrf
                    @method('POST')
                    <div class="form-group">
                        <label for="startTime" class="col-md-2 control-label ">Start Time *</label>
                        <div class="col-md-4">
                            <input type="time" id="startTime" maxlength="190" name="startTime"  value="{{ old('startTime') }}" class="form-control datetimepicker" />
                        </div>
                        @if ($errors->has('startTime'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('startTime') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group" >
                        <label for="endTime" class="col-md-2 control-label">End Time *</label>
                        <div class="col-md-4" >

                            <input  type="time" id="endTime" maxlength="190" name="endTime"   value="{{ old('endTime') }}" class="form-control  datetimepicker  " />

                        </div>
                        @if ($errors->has('endTime'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('endTime') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn blue" id="save" value="Save">
                            <input type="button" class="btn black" name="cancel" id="cancel" value="Cancel">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
<!-- END PAGE CONTENT-->
@stop

@section('footer-js')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/ckeditor/ckeditor.js') }}"></script>
<script src="{!! URL::to('assets/admin/scripts/core/app.js') !!}"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" integrity="sha256-b5ZKCi55IX+24Jqn638cP/q3Nb2nlx+MH/vMMqrId6k=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" integrity="sha256-5YmaxAwMjIpMrVlK84Y/+NjCpKnFYa8bWWBbUHSBGfU=" crossorigin="anonymous"></script>
<script>
jQuery(document).ready(function() {

    // initiate layout and plugins
    App.init();
    Admin.init();
    $('#cancel').click(function() {
        window.location.href = "{!! URL::route('work-time.index') !!}";
    });
});



</script>
<script type="text/javascript">

</script>
@stop

resources/views/admin/workTime/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">{{ $pageTitle ?? '' }} <small></small></h3>
        {{ Breadcrumbs::render('work-time.edit', $workTime ?? '') }}
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">

        {{--@include('admin.partials.errors')--}}

        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">

            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-edit"></i> {{ $pageTitle ?? '' }}
                </div>
            </div>

            <div class="portlet-body">

                <h4>&nbsp;</h4>

                <form method="POST" action="{{ route('work-time.update', $workTime->id) }}" class="form-horizontal" role="form">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="start_time" class="col-md-2 control-label">Start Time *</label>
                        <div class="col-md-4">
                            <input type="time" id="start_time" maxlength="190" name="start_time" value="{{$workTime->start_time}}" class="form-control" />
                        </div>
                        @if ($errors->has('start_time'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('start_time') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="end_time" class="col-md-2 control-label">End Time *</label>
                        <div class="col-md-4">
                            <input type="time" id="end_time" maxlength="190" name="end_time" value="{{$workTime->end_time}}" class="form-control" />
                        </div>
                        @if ($errors->has('end_time'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('end_time') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn blue" id="save" value="Save">
                            <input type="button" class="btn black" name="cancel" id="cancel" value="Cancel">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
<!-- END PAGE CONTENT-->
@stop

@section('footer-js')
{{--<script type="text/javascript" src="{!! URL::to('assets/admin/plugins/ckeditor/ckeditor.js') !!}"></script>--}}
<script src="{{ asset('assets/admin/scripts/core/app.js')}}"></script>
<script>
jQuery(document).ready(function() {
    // initiate layout and plugins
    App.init();
    Admin.init();
    $('#cancel').click(function() {
        window.location.href = "{!! URL::route('work-time.index') !!}";
    });

});


</script>
@stop

resources/views/admin/workTime/index.blade.php
@extends('admin.layouts.app')

@section('css')
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="{{ URL::to('assets/admin/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{!! URL::to('assets/admin/plugins/select2/select2.css') !!}"/>
<link rel="stylesheet" type="text/css" href="{!! URL::to('assets/admin/plugins/select2/select2-metronic.css') !!}"/>
{{--<link rel="stylesheet" href="{!! URL::to('assets/admin/plugins/data-tables/DT_bootstrap.css') !!}"/>--}}
<!-- END PAGE LEVEL STYLES -->
@stop

@section('content')
<!-- BEGIN PAGE HEADER-->
@include('admin.partials.errors')
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">{{ $pageTitle ?? '' }} <small></small></h3>
        {{ Breadcrumbs::render('work-time.index') }}
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <!-- Action buttons Code Start -->
        <div class="row">
            <div class="col-md-12">
                <!-- Add New Button Code Moved Here -->
                <div class="table-toolbar pull-right">
                    <div class="btn-group">
                       {{-- @if(HasPermissionAccess($userPermissoins['type'],'add',$userPermissoins['permissions']))
                        <a href="{!! URL::route('work-time.create') !!}" id="sample_editable_1_new" class="btn blue">
                            Add <i class="fa fa-plus"></i>
                        </a>
                        @endif--}}
                    </div>
                </div>
                <!-- Add New Button Code Moved Here -->
            </div>
        </div>
        <!-- Action buttons Code End -->



        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">

            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-list"></i> {{ $pageTitle ?? '' }}
                </div>
            </div>

            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover yajrabox" id="sample_1">
                    <thead>
                        <tr>
                            <th style="width: 5%" class="text-center" >ID</th>
                            <th style="width: 40%" class="text-center" >Start time</th>
                            <th style="width: 40%" class="text-center" > End time</th>
                            <th style="width: 10%" class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
<!-- END PAGE CONTENT-->
@stop

@section('footer-js')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/admin/plugins/select2/select2.min.js') }}"></script>

{{--<script type="text/javascript" src="{!! URL::to('assets/admin/plugins/data-tables/jquery.dataTables.js') !!}"></script>
<script type="text/javascript" src="{!! URL::to('assets/admin/plugins/data-tables/DT_bootstrap.js') !!}"></script>--}}
<!-- END PAGE LEVEL PLUGINS -->
<script src="{{ asset('assets/admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>

<script src="{{ asset('assets/admin/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/admin/scripts/core/app.js') }}"></script>
<script src="{{ asset('assets/admin/scripts/custom/pages.js') }}"></script>
<script src="{{ asset('assets/admin/scripts/custom/user-administrators.js') }}"></script>

<script>

    jQuery(document).ready(function() {
        // initiate layout and plugins
        App.init();
        Admin.init();
        $('#cancel').click(function() {
            window.location.href = "{!! URL::route('work-time.index') !!}";
        });
    });
    $(function () {
        appConfig.set('yajrabox.ajax', '{{ route('work-time.data') }}');
        appConfig.set('dt.order', [0, 'desc']);
        appConfig.set('yajrabox.ajax.data', function (data) {
            data.status = jQuery('select[name=status]').val();
        });
        appConfig.set('yajrabox.columns', [
            {data: 'id',   orderable: true,   searchable: false, className:'text-center'},
            {data: 'start_time',   orderable: true,   searchable: true, className:'text-center'},
            {data: 'end_time',         orderable: true,    searchable: true, className:'text-center'},
            {data: 'action',            orderable: false,   searchable: false, className:'text-center'}

        ]);
    })

</script>
@stop