routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('admin', 'IndexController@index')->name('login'); // for redirection purpose


/*Route::name('/')->group(
    function () {*/

        Route::get('/', 'IndexController@index');
        Route::group(['middleware' => 'backendAuthenticate'], function () {

            Route::get('/dashboard', [
                'uses' => 'DashboardController@index',
                'as' => 'dashboard.index'
            ]);

            Route::group(['middleware' => ['backendAuthenticate','PermissionHandler']], function () {


                ###role management routes###
                Route::resource('role', 'RoleController');
                Route::get('role/set-permissions/{role}', 'RoleController@setPermissions')->name('role.set-permissions');
                Route::post('role/set-permissions/update/{role}', 'RoleController@setPermissionsUpdate')->name('role.set-permissions.update');

                ###Sub Admins###
                Route::get('sub-admin/data', 'SubAdminController@data')->name('sub-admin.data');
                Route::resource('sub-admin', 'SubAdminController');
                Route::get('sub-admin/active/{record}', 'SubAdminController@active')->name('sub-admin.active');
                Route::get('sub-admin/inactive/{record}', 'SubAdminController@inactive')->name('sub-admin.inactive');


                Route::get('zones/data', 'ZonesController@data')->name('zones.data');
                Route::resource('zones', 'ZonesController');


                Route::get('work-time/data', 'WorkTimeController@data')->name('work-time.data');
                Route::resource('work-time', 'WorkTimeController');


                Route::get('work-type/data', 'WorkTypeController@data')->name('work-type.data');
                Route::resource('work-type', 'WorkTypeController');

                Route::get('joey-document-verification/data', 'JoeyDocumentVerificationController@data')->name('joey-document-verification.data');
                Route::resource('joey-document-verification', 'JoeyDocumentVerificationController');
                Route::get('joeyDocumentVerification/status/update/statusUpdate', 'JoeyDocumentVerificationController@statusUpdate')->name('joey-document-verification.statusUpdate');


                Route::get('training/data', 'TrainingController@data')->name('training.data');
                Route::resource('training', 'TrainingController');

                Route::get('categores/data', 'CategoresController@data')->name('categores.data');
                Route::resource('categores', 'CategoresController');


                Route::get('quiz-management/data', 'QuizController@data')->name('quiz-management.data');
                Route::resource('quiz-management', 'QuizController');


                Route::get('job-type/data', 'JobTypeController@data')->name('job-type.data');
                Route::resource('job-type', 'JobTypeController');


                Route::get('order-category/data', 'OrderCategoryController@data')->name('order-category.data');
                Route::resource('order-category', 'OrderCategoryController');

                Route::get('vendors/data', 'VendorsController@data')->name('vendors.data');
                Route::resource('vendors', 'VendorsController');

                Route::get('joey-checklist/data', 'JoeyChecklistController@data')->name('joey-checklist.data');
                Route::resource('joey-checklist', 'JoeyChecklistController');


                Route::get('basic-vendor/data', 'BasicVendorController@data')->name('basic-vendor.data');
                Route::resource('basic-vendor', 'BasicVendorController');


                Route::get('basic-category/data', 'BasicCategoryController@data')->name('basic-category.data');
                Route::resource('basic-category', 'BasicCategoryController');

                Route::get('vendor-score/data', 'VendorScoreController@data')->name('vendor-score.data');
                Route::resource('vendor-score', 'VendorScoreController');

                Route::get('category-score/data', 'CategoryScoreController@data')->name('category-score.data');
                Route::resource('category-score', 'CategoryScoreController');


                Route::resource('site-settings', 'SiteSettingsController');
                Route::resource('countries', 'CountriesController');
                Route::resource('cities', 'CitiesController');


                Route::get('/edit-profile', [
                    'uses' => 'UsersController@editProfile',
                    'as' => 'users.edit-profile'
                ]);

                Route::post('/edit-profile', [
                    'uses' => 'UsersController@updateEditProfile',
                    'as' => 'users.edit-profile'
                ]);


                Route::get('/change-password', [
                    'uses' => 'UsersController@changePassword',
                    'as' => 'users.change-password'
                ]);


                Route::post('/change-password', [
                    'uses' => 'UsersController@processChangePassword',
                    'as' => 'users.change-password'
                ]);
            });
        }
        );
          Route::get('/login', [
                'uses' => 'Auth\LoginController@showLoginForm',
                'as' => 'login'
            ]);

        Route::post('/login', [
            'uses' => 'Auth\LoginController@login',
            'as' => 'login'
        ]);


        Route::any('/logout', [
            'uses' => 'Auth\LoginController@logout',
            'as' => 'logout'
        ]);

        Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
        Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('reset-password', 'auth\ResetPasswordController@reset_password_from_show')->name('reset.password.show');
        Route::post('reset-password-update', 'auth\Resetpasswordcontroller@reset_password_update')->name('reset.password.update');
  //}
//);

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Auth::routes();

Route::get('/', 'HomeController@index')->name('index');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::post('contact', 'HomeController@processContact')->name('process-contact');
Route::get('categories/{slug}', 'HomeController@categoryDetails')->name('category.details');

Route::get('home', function () {
    return redirect('/');
});

Route::get('thank-you', function () {
    return view('thankYou');
});

/*Route::get('/clear-cache', function() {
	Artisan::call('cache:clear');
   	Artisan::call('config:clear');
	Artisan::call('config:cache');
	Artisan::call('view:clear');
	Artisan::call('route:clear');
	return 'Cache cleared!';
});*/

routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
Route::get('reset/success', function (Request $request) {
    return view('admin.auth.passwords.success');
});
Route::get('joeyco-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('apidocs', static function (Request $request) {
    return view('documentation.index');
});

Route::get('json-file', static function(Request $request){


    //Get Json File
    $file = file_get_contents(base_path('webservices.json'));

    $decodeFile =  json_decode($file, true);

    //Replace Host With Current Host
    $decodeFile['host'] = request()->getHttpHost();

    //Set Base Path
    $decodeFile['basePath'] = str_replace('json-file', 'api/v1', request()->getRequestUri());

    //Set Scheme According To Request
    $decodeFile['schemes'] = $request->isSecure() ? ['https'] : ['http'];

    return response()->json($decodeFile);

})->name('json-url');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/partials/_pdfFiles.blade.php
<div class="col-md-8 col-md-offset-2">
    <p><small><em>Right click on any image above, and choose copy image. Then paste in the text editor below.</em></small></p>
</div>

<div class="col-md-8 col-md-offset-2" style="overflow-y:scroll; overflow-x:hidden; height:100px; margin-top:20px;">
    @if (isset($mediaFile) && count($mediaFile) > 0)
	    <ol>
	        @foreach ($mediaFile as $media)
	            @if (getFileExtension($media->filename) == 'pdf')
	                <li><a href="{!! asset(uploadsDir().$media->filename) !!}" target="_blank">{!! $media->caption !!}</a></li>
	            @endif
	        @endforeach
	    </ol>
    @endif
</div>

<div class="col-md-8 col-md-offset-2">
    <p><small><em>Right click on any PDF link above, and choose copy link address. Then paste in the text editor > Link icon below.</em></small></p>
</div>

resources/views/admin/partials/breadcrumbs.blade.php
@if (count($breadcrumbs))

    <ul class="page-breadcrumb breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li>
                    @if ($loop->first)
                        <i class="fa fa-home"></i>
                    @endif
                    <a href="{{ $breadcrumb->url }}">{!! $breadcrumb->title !!}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
            @else
                <li class="active">
                    @if ($loop->first)
                        <i class="fa fa-home"></i>
                    @endif
                    {!! $breadcrumb->title !!}
                </li>
            @endif

        @endforeach
    </ul>

@endif

resources/views/admin/partials/dashboard-cards.blade.php
<div class="row">

    @if(can_view_cards('sub_admin_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-users"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($subAdmin) ? $subAdmin : 0 !!}
                    </div>
                    <div class="desc">
                        Sub Admins
                    </div>
                </div>
                <a class="more" href="{!! route('sub-admin.index') !!}">
                    See Sub Admins <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
    @if(can_view_cards('job_type_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-tasks"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($jobType) ? $jobType : 0 !!}
                    </div>
                    <div class="desc">
                        Job Types
                    </div>
                </div>
                <a class="more" href="{!! route('job-type.index') !!}">
                    See Job Types <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
    @if(can_view_cards('order_category_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-tag"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($orderCategory) ? $orderCategory : 0 !!}
                    </div>
                    <div class="desc">
                        Order Categories
                    </div>
                </div>
                <a class="more" href="{!! route('order-category.index') !!}">
                    See Order Categories <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
</div>

<div class="row">
    @if(can_view_cards('zones_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-cog"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($zones) ? $zones : 0 !!}
                    </div>
                    <div class="desc">
                        Zones
                    </div>
                </div>
                <a class="more" href="{!! route('zones.index') !!}">
                    See Zones <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
    @if(can_view_cards('work_time_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-clock-o"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($worktime) ? $worktime : 0 !!}
                    </div>
                    <div class="desc">
                        Work Times
                    </div>
                </div>
                <a class="more" href="{!! route('work-time.index') !!}">
                    See Work Times <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
    @if(can_view_cards('work_type_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-briefcase"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($worktype) ? $worktype : 0 !!}
                    </div>
                    <div class="desc">
                        Work Types
                    </div>
                </div>
                <a class="more" href="{!! route('work-type.index') !!}">
                    See Work Types <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
</div>

<div class="row">
    @if(can_view_cards('training_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-video-camera"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($training) ? $training : 0 !!}
                    </div>
                    <div class="desc">
                        Training Videos
                    </div>
                </div>
                <a class="more" href="{!! route('training.index') !!}">
                    See Training Videos<i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    @endif
    @if(can_view_cards('quiz_management_card_count',$dashbord_cards_rights))
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="dashboard-stat dashboard-cart-box-one class green">
                <div class="visual" style="margin-right: 12px;">
                    <i class="fa fa-question"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {!! isset($quiz) ? $quiz : 0 !!}
                    </div>
                    <div class="desc">
                        Quizzes
                    </div>
                </div>
                <a class="more" href="{!! route('quiz-management.index') !!}">
                    See Quizzes <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>

    @endif

</div>
<div class="clearfix"></div>
<!-- Dashboard cards close -->

resources/views/admin/partials/errors.blade.php
@if (isset($errors) && count($errors) > 0)
    <div class="alert alert-danger custom">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        @foreach ($errors->all() as $error)
            {{ $error }}<br />
        @endforeach
    </div>
@endif

@if (Session::has('error'))
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {!! Session::pull('error') !!}
    </div>
@endif

@if (Session::has('success'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {!! Session::pull('success') !!}
    </div>
@endif